name: Testing

on:
  workflow_dispatch:  

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Debug 
        run: |
          echo "${{env.TEST}}" >> temp.txt
          echo user.email "${{env.MAIL}}"
          echo user.email "${{secrets.MAIL}}"
