name: Scheduled Commit

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:  

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          date >>temp.txt

      - name: Commit changes
        run: |
          git config --local user.name "Hapkin"
          git config --local user.email ${{ secrets.ENVMAIL }}
          git commit -m "new dawn." -- temp.txt
          git push
